[build]
  command = "npm run build:client"
  publish = "dist"
  environment = { NODE_VERSION = "18", SECRETS_SCAN_ENABLED = "false" }

# Handle client-side routing - redirect all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
